// react/car/src/views/login/index.jsx
import React, { Component } from "react";
import "../../mock/index";
import axios from "axios";
import ErrorWithStack from "jest-util/build/ErrorWithStack";
class Login extends Component {
  state = {
    name: "",
    pwd: ""
  };
  render() {
    let { name, pwd } = this.state;
    return (
      <div className="login">
        <input
          placeholder="Username"
          value={name}
          name="name"
          onChange={this.Changes.bind(this)}
        />

        <input
          type="password"
          placeholder="Password"
          value={pwd}
          name="pwd"
          onChange={this.Changes.bind(this)}
        />

        <button onClick={this.Submit.bind(this)}>登陆</button>
      </div>
    );
  }
  Changes(e) {
    let key = e.target.name;
    console.log(key, e.target.value);
    this.setState({ [key]: e.target.value });
  }
  Submit() {
    let { name, pwd } = this.state;
    console.log(name, pwd);
    window.localStorage.user = name;
    this.props.history.go(-1);
    fetch("/api/login")
      .then(res => {
        return res.json();
      })
      .then(data => {
        console.log(data);
      });
    // axios.post("/api/login").then(res => {
    //   console.log(res);
    //   if (res.data.code == 1) {
    // window.localStorage.user = name;
    //   this.props.history.go(-1);
    //   }
    // });
  }
}

export default Login;

// vue/book/src/views/login/login.vue
<template>
  <div>
      <input placeholder="请输入用户名" v-model="name"/>
      <input placeholder="请输入密码" v-model="pwd"/>
      <button @click="goToLogin">登录</button>
  </div>
</template>

<script>
import '@/mock/index'
export default {
  data(){
    return{
      name:'',
      pwd:''
    }
  },
  methods:{
    changeInput(e){
      console.log(31231231);
      this.name = e.target.value;
    },
    goToLogin(){
      this.$http.post('/api/login',{name:this.name,pwd:this.pwd}).then((res)=>{
        console.log(res);
        if(res.data.code == 1){
          window.localStorage.user = this.name;
          this.$router.push({path:this.$route.query.redirect});
        }
      });
      console.log(this.name,this.pwd);
    }
  }
}
</script>

<style>
</style>
